name: Test and publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Test
        run: |
          npm install
          npm run test
      - name: E2E test with mkpasswd
        run: |
          sudo apt install -y whois
          npm install
          npm run e2e
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish codecov report
        run: |
          npm run coverage
          ./node_modules/.bin/codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish package
        if: "!contains(github.event.head_commit.message, 'skip-publish')"
        uses: mikeal/merge-release@v4.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build docs
        if: "!contains(github.event.head_commit.message, 'skip-docs')"
        run: |
          npm run docs -- --gitRevision ${GITHUB_SHA}
      #      - name: Find published version
      #        run: |
      #          echo "::set-env name=LATEST_VERSION::$(npm view sha512-crypt-ts version)"
      - name: Copy docs includes
        run: |
          cp -R ./docs_include/* ./docs
      - name: Publish docs
        if: "!contains(github.event.head_commit.message, 'skip-docs')"
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
#          TARGET_FOLDER: ${{ env.LATEST_VERSION }}


